### ISSUE TITLE
Black Laser - Feedrate problem

### ISSUE THREAD

**Issue by ajfisher** [CCHS-Melbourne/Laser-Cutters#1]
Looking at this feedrate issue it looks like these calculations of the trapezoid are different in the newer version:

https://github.com/CCHS-Melbourne/LaserCutter/blob/master/Marlin/stepper.cpp#L318

**Comment by PancakeLegend** [comment]
Closing all issues relating to the Black Laser. It has been out of commission for 4 years. If it is to be used, it needs new firmware and a thorough recommissioning process. A great project for anyone interested.
