### ISSUE TITLE
Black Laser - Pauses at the start and end of each path.

### ISSUE THREAD

**Issue by PancakeLegend** [CCHS-Melbourne/Laser-Cutters#3]
Laser pauses and fires for a second before starting a new path and pauses after path before moving to next. Suspect post processor code for spinning up spindle / lowering / raising spindle / G04 Dwell??

The firing of the laser impacts the quality of the work significantly.

**Comment by mage0r** [comment]
Laser 02 firmware has "fire on G1" active.  The way Pronterface jogs the head is using G1 commands.  Could this be related?

**Comment by PancakeLegend** [comment]
Has anyone tried solving the 'fire on jog' issue?

**Comment by mage0r** [comment]
It has to be solved in Firmware and it's possible nobody has the firmware in use.

Now we have alternative lasers, people might be a little less nervous about changing things.

**Comment by PancakeLegend** [comment]
Closing all issues relating to the Black Laser. It has been out of commission for 4 years. If it is to be used, it needs new firmware and a thorough recommissioning process. A great project for anyone interested.
